apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: lexmarkkubernetes/my-app:prod  # Use the correct tag for the dev environment
          ports:
            - containerPort: 8080
