# k8s/overlays/dev/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-my-app-ingress
spec:
  rules:
    - host: prod.myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-my-app
                port:
                  number: 80

