apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lexmarkCS499/lexmarkResource.git
    targetRevision: prod
    path: 'k8s/overlays/prod'  # Use the prod overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: prod  # Namespace for the prod environment
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true  # Create prod namespace if it doesn't exist
