apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app  # Ensure the labels match the selector
    spec:
      containers:
        - name: lexmarkkubernetes
          image: lexmarkkubernetes/my-app:866a0d5242a0d38cd94c808c8899f8f62875fdba
          ports:
            - containerPort: 8080
