#k8s/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: lexmarkkubernetes
          image: lexmarkkubernetes/my-app:120f9c5e8c57245bd3a2eeecf5c32de691ae4fdb
          ports:
            - containerPort: 8080
