apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app  # Ensure the labels match the selector
    spec:
      containers:
        - name: lexmarkkubernetes
          image: lexmarkkubernetes/my-app:d3ab4cc683f23638caee2180dab6e1fd28499ff6
          ports:
            - containerPort: 8080
