#k8s/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: lexmarkkubernetes
          image: lexmarkkubernetes/my-app:a5f657601844408dbc32055c3c3c5ce681f0647a
          ports:
            - containerPort: 8080
