apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-myapp-argo-application
  namespace: argocd
spec:
  project: default

  # Source configuration: Where to pull the application manifests from
  source:
    repoURL: https://github.com/lexmarkCS499/lexmarkResource.git
    targetRevision: dev
    path: 'k8s/overlays/dev'  # Use the dev overlay for this environment

  # Destination configuration: Where to deploy the application in Kubernetes
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server (in-cluster)
    namespace: dev  # The namespace for the dev environment

  # Sync policy: Automate sync and healing
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true  # Create the dev namespace if it doesn't exist
