#k8s/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
  - ../../base
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: dev-app
resources:
  - ingress.yaml