apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev  # Ensure this is set to `dev`
resources:
  - ../../base  # Pointing to the base manifests
patchesStrategicMerge:
  - deployment.yaml  # Apply the dev-specific deployment patch
